[pytest]
log_auto_indent = "Off"
log_cli = false
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_level = "INFO"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_file = "logs/pytest-logs.txt"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
log_file_format = "%(asctime)s %(levelname)s %(message)s"
log_file_level = "INFO"
log_file_mode = "a"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_level = "INFO"

# addopts = [
#     # "-rf", 

# "-qq",
# "--maxfail=1", 
# "--numprocesses=auto", 
# "--tb=no",
# "--no-header",
# "--show-capture=all",
# "--disable-warnings",
# "-p", "no:inline_snapshot",
# ]

addopts = [
    # "-rf", 

# "-qq",
"--maxfail=1", 
"--numprocesses=auto", 
"--tb=short",
"--xfail-tb", 
"--no-header",
"--show-capture=all",
"--disable-warnings",
"-p", "no:inline_snapshot",
]


filterwarnings = [
  "ignore::DeprecationWarning",
]
testpaths = ["../tests"]
verbosity_test_cases = "0"